/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Employee;

import View.Employee.LoginEmployee;
import Model.FlightDB;
import Controller.Employee;
import Controller.Flight;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import projet.DriverConnection;

/**
 *
 * @author Tommy
 */
public class MainPageEmployee extends javax.swing.JFrame {
    private final Employee employee;
    /** Creates new form MainPageEmployee */
    public MainPageEmployee(Employee employee) throws SQLException {
        initComponents();
        this.employee = employee;
        showFlightInTable();
        setVisible(true);
    }

    
    public MainPageEmployee() {
        initComponents();
        this.employee = null;
        setVisible(true);
    }
    
    public ArrayList<Flight> getFlightList() throws SQLException {
        
        ArrayList<Flight> flightList = new ArrayList<Flight>();
        
        try {
            Connection conn = DriverConnection.getConnection();
            String query = "SELECT * FROM `flights`";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            Flight flight;
            
            while(rs.next()) {
                
                flight = new Flight(rs.getString("dcity"), rs.getString("acity"), rs.getString("ddate"), rs.getString("adate"), Integer.parseInt(rs.getString("flightno"))
                        , rs.getString("dtime"), rs.getString("atime"), Double.parseDouble(rs.getString("price")), rs.getString("class"));
                
                flightList.add(flight);
            }
        }
        
        catch (SQLException e) {
            e.printStackTrace();
        }
        
        return flightList;
    }
    
    
    public void showFlightInTable() throws SQLException 
    {
        
        ArrayList<Flight> flightList = getFlightList();
        DefaultTableModel model = new DefaultTableModel();
        
        model.setColumnIdentifiers(new Object[]{"Flight no", "Departure city", "Arrival city", "Departure date", "Arrival date", "Departure time", "Arrival time", "Price", "Class"});
        Object[] row = new Object[9];
        
        for (int i = 0; i < flightList.size() ; i++) {
            
            row[0] = flightList.get(i).getFlightno();
            row[1] = flightList.get(i).getDcity();
            row[2] = flightList.get(i).getAcity();
            row[3] = flightList.get(i).getDdate();
            row[4] = flightList.get(i).getAdate();
            row[5] = flightList.get(i).getDtime();
            row[6] = flightList.get(i).getAtime();
            row[7] = flightList.get(i).getPrice();
            row[8] = flightList.get(i).getFclass();
            
            model.addRow(row);
        }
        jTable1.setModel(model);
    }
    
    public void executeSQLQuery(String query, String message) {
        Connection con = DriverConnection.getConnection();
        Statement stmt;
        
        try {
            stmt = con.createStatement();
            if ((stmt.executeUpdate(query)) == 1) {
                
                // Refresh JTable data
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                model.setRowCount(0);
                showFlightInTable();
                JOptionPane.showMessageDialog(null, "Data "+message+ " successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Data not " +message);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        departureCityTxtField = new javax.swing.JTextField();
        departureDateTxtField = new javax.swing.JTextField();
        flightNoTxtField = new javax.swing.JTextField();
        priceTxtField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InsertBtn = new javax.swing.JButton();
        arrivalTimeTxtField = new javax.swing.JTextField();
        departureTimeTxtField = new javax.swing.JTextField();
        arrivalDateTxtField = new javax.swing.JTextField();
        arrivalCityTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        classTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Workbench");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        LoginBtn.setBackground(new java.awt.Color(255, 153, 0));
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jLabel3.setText("Departure City ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 103, -1, -1));

        jLabel5.setText("Departure date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 189, -1, -1));

        jLabel7.setText("Flight no");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 52, 74, -1));

        jLabel10.setText("Price");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 72, -1));

        jLabel11.setText("Class");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 72, -1));

        departureCityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureCityTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(departureCityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 103, 93, -1));

        departureDateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureDateTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(departureDateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 186, 93, -1));
        jPanel1.add(flightNoTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 52, 93, -1));
        jPanel1.add(priceTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 93, -1));

        updateBtn.setBackground(new java.awt.Color(255, 153, 0));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 359, 183, 43));

        deleteBtn.setBackground(new java.awt.Color(255, 153, 0));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 358, 183, 44));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 204, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Departure city", "Arrival city", "Departure date", "Return date", "Flight no", "Departure time", "Arrival time", "Price", "Class"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 52, 690, 278));

        InsertBtn.setBackground(new java.awt.Color(255, 153, 0));
        InsertBtn.setText("Insert");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InsertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 354, 183, 52));
        jPanel1.add(arrivalTimeTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 310, 93, -1));
        jPanel1.add(departureTimeTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 264, 93, -1));
        jPanel1.add(arrivalDateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 224, 93, -1));

        arrivalCityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalCityTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(arrivalCityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 148, 93, -1));

        jLabel2.setText("Arrival city");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 151, 74, -1));

        jLabel4.setText("Arrival date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 224, 74, -1));

        jLabel6.setText("Departure time");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 267, -1, -1));

        jLabel8.setText("Arrival time");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 313, 72, -1));
        jPanel1.add(classTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 93, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/fond_colore.png"))); // NOI18N
        jLabel1.setText("Back");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        new LoginEmployee();
        dispose();
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void departureCityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureCityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureCityTxtFieldActionPerformed

    private void departureDateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureDateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureDateTxtFieldActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        /// Display selected row in text fields
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        flightNoTxtField.setText(model.getValueAt(i,0).toString());
        departureCityTxtField.setText(model.getValueAt(i,1).toString());
        arrivalCityTxtField.setText(model.getValueAt(i,2).toString());
        departureDateTxtField.setText(model.getValueAt(i,3).toString());
        arrivalDateTxtField.setText(model.getValueAt(i,4).toString());
        departureTimeTxtField.setText(model.getValueAt(i,5).toString());
        arrivalTimeTxtField.setText(model.getValueAt(i,6).toString());
        priceTxtField.setText(model.getValueAt(i,7).toString());
        classTxtField.setText(model.getValueAt(i,8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO `flights`(`dcity`, `acity`, `ddate`, `adate`, `flightno`, `dtime`, `atime`, `price`, `class`) VALUES ('"+departureCityTxtField.getText()+"','"+arrivalCityTxtField.getText()+"','"+departureDateTxtField.getText()+"','"+arrivalDateTxtField.getText()+"',"
                + "'"+flightNoTxtField.getText()+"','"+departureTimeTxtField.getText()+"','"+arrivalTimeTxtField.getText()+"','"+priceTxtField.getText()+"','"+classTxtField.getText()+"')";
        
        executeSQLQuery(query, "Flight inserted");
        
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE `flights` SET `dcity`='"+departureCityTxtField.getText()+"',`acity`='"+arrivalCityTxtField.getText()+"',`ddate`='"+departureDateTxtField.getText()+"',`adate`='"+arrivalDateTxtField.getText()+"'"
                + ",`dtime`='"+departureTimeTxtField.getText()+"',`atime`='"+arrivalTimeTxtField.getText()+"',`price`='"+priceTxtField.getText()+"',`class`='"+classTxtField.getText()+"' WHERE `flightno` = "+flightNoTxtField.getText();
        executeSQLQuery(query, "Flight updated");
        
       /// `dcity`='"+departureCityTxtField.getText()+"',
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM `flights` WHERE `flightno`= "+flightNoTxtField.getText();
        executeSQLQuery(query, "Flight deleted");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void arrivalCityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalCityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalCityTxtFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new HomePageEmployee(this.employee);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField arrivalCityTxtField;
    private javax.swing.JTextField arrivalDateTxtField;
    private javax.swing.JTextField arrivalTimeTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField classTxtField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField departureCityTxtField;
    private javax.swing.JTextField departureDateTxtField;
    private javax.swing.JTextField departureTimeTxtField;
    private javax.swing.JTextField flightNoTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
