/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Member;

import Controller.Flight;
import Controller.Member;
import Controller.Ticket;
import View.ChooseType;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import projet.DriverConnection;

/**
 *
 * @author Tommy
 */
public class MainPage extends javax.swing.JFrame {

    private final Member user;
    /**
     * Creates new form MainPage
     * 
     * 
     */
    
    public MainPage(Member user) {
        initComponents();
        this.user = user;
        jLabel1.setText("Welcome " +user.getName());
        setVisible(true);
        
         ViewFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                viewFlightBtnActionPerformed(evt);
            }
        });
         
         SearchFlightBtn.setText("Search for a flight");
        SearchFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightBtnActionPerformed(evt);
            }
        });
    }
    
    
    
    public MainPage() {
        initComponents();
        this.user = null;
        setVisible(true);
        
        
        ViewFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                viewFlightBtnActionPerformed(evt);
            }
        });
        
        
        SearchFlightBtn.setText("Search for a flight");
        SearchFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightBtnActionPerformed(evt);
            }
        });
        
        
        
    }

    
    public ArrayList<Flight> getFlightList() throws SQLException {
        
        ArrayList<Flight> flightList = new ArrayList<Flight>();
        
        try {
            Connection conn = DriverConnection.getConnection();
            String query = "SELECT * FROM `flights`";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            Flight flight;
            
            while(rs.next()) {
                
                flight = new Flight(rs.getString("dcity"), rs.getString("acity"), rs.getString("ddate"), rs.getString("adate"), Integer.parseInt(rs.getString("flightno"))
                        , rs.getString("dtime"), rs.getString("atime"), Double.parseDouble(rs.getString("price")), rs.getString("class"));
                
                flightList.add(flight);
            }
        }
        
        catch (SQLException e) {
            e.printStackTrace();
        }
        
        return flightList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        SearchFlightBtn = new javax.swing.JButton();
        ViewFlightBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome, Guest");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 150, 70));

        LoginBtn.setBackground(new java.awt.Color(255, 153, 0));
        LoginBtn.setText("LOGIN");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 110, 40));

        SearchFlightBtn.setBackground(new java.awt.Color(255, 153, 0));
        SearchFlightBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchFlightBtn.setText("SEARCH FLIGHTS");
        getContentPane().add(SearchFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, 70));

        ViewFlightBtn.setBackground(new java.awt.Color(255, 153, 0));
        ViewFlightBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewFlightBtn.setText("VIEW ALL FLIGHTS");
        getContentPane().add(ViewFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 150, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("What do you want to do today ?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 420, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/map.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 520, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/fond_colore.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        new Login();
        dispose();
    }//GEN-LAST:event_LoginBtnActionPerformed

 
      private void viewFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try {
            // TODO add your handling code here:
            new ViewFlights(user);
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        dispose();
      }

       private void searchFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {           
            new SearchFlight(this.user);
            dispose();
       }
     
     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
        new ChooseType();
        dispose();
    }     
       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
        
    }
    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton SearchFlightBtn;
    private javax.swing.JButton ViewFlightBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
