/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Member;




import View.Member.MainPage;
import Controller.Flight;
import Controller.Guest;
import Controller.Member;
import Controller.Ticket;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import projet.DriverConnection;

/**
 *
 * @author Tommy
 */
public class SearchFlight extends javax.swing.JFrame {

    private final Member member;
    private final Guest guest;
    /**
     * Creates new form SearchFlight
     */
    public SearchFlight(Member member) {
        this.member = member;
        this.guest = null;
        
        initComponents();
        findFlight();
        setVisible(true);

        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

    }

    public SearchFlight(Guest guest) {
        this.guest = guest;
        this.member = null;
        
        initComponents();
        findFlight();
        setVisible(true);

        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        
    }
    public SearchFlight() {
        this.member = null;
        this.guest = null;
        System.out.println("Salut " +this.member.getName());
        initComponents();
        findFlight();
        setVisible(true);
        
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
    }

    public ArrayList<Flight> flightList(String City, String City2, String Date, String Date2, String classe) {
        ArrayList<Flight> flightList = new ArrayList<Flight>();
        Statement st;
        ResultSet rs;

        try {

            Connection conn = DriverConnection.getConnection();

            st = conn.createStatement();
            String searchQuery = "SELECT * FROM `flights` WHERE `dcity` LIKE '%" + City + "%' AND `acity` LIKE '%" + City2 + "%' AND `ddate` LIKE '%" + Date + "%' AND `adate` LIKE '%" + Date2 + "%' AND `class` LIKE '%" + classe + "%' ";

            rs = st.executeQuery(searchQuery);
            Flight flight;

            while (rs.next()) {

                flight = new Flight(rs.getString("dcity"), rs.getString("acity"), rs.getString("ddate"), rs.getString("adate"), Integer.parseInt(rs.getString("flightno")),
                         rs.getString("dtime"), rs.getString("atime"), Double.parseDouble(rs.getString("price")), rs.getString("class"));

                flightList.add(flight);
            }
        } catch (Exception ex) {
            System.out.println("");
        }

        return flightList;
    }

    public void findFlight() {
        ArrayList<Flight> flightList = flightList(jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), jTextField4.getText(), (String) jComboBox1.getSelectedItem());
        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(new Object[]{"Flight no", "Departure city", "Arrival city", "Departure date", "Arrival date", "Departure time", "Arrival time", "Price", "Class"});
        Object[] row = new Object[9];

        for (int i = 0; i < flightList.size(); i++) {

            row[0] = flightList.get(i).getFlightno();
            row[1] = flightList.get(i).getDcity();
            row[2] = flightList.get(i).getAcity();
            row[3] = flightList.get(i).getDdate();
            row[4] = flightList.get(i).getAdate();
            row[5] = flightList.get(i).getDtime();
            row[6] = flightList.get(i).getAtime();
            row[7] = flightList.get(i).getPrice();
            row[8] = flightList.get(i).getFclass();

            model.addRow(row);
        }
        jTable1.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 120, 50));

        BackBtn.setBackground(new java.awt.Color(255, 153, 51));
        BackBtn.setText("Back");
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 30));

        searchBtn.setBackground(new java.awt.Color(255, 153, 0));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 110, 50));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 180, 40));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 180, 40));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 180, 40));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 180, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Business" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 40));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 204, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight no", "From", "To", "Depart", "Return", "Departure time", "Arrival time", "Price", "Class"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 820, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("From");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("To");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Depart");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Return");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/fond_colore.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 590));

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 0, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        findFlight();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (member == null) {
            new MainPage(this.guest);
        } 
        if (guest == null) {
            new MainPage(this.member);
        }
        dispose();
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();

        
        String flightno = model.getValueAt(index, 0).toString();
        String dcity = model.getValueAt(index, 1).toString();
        String acity = model.getValueAt(index, 2).toString();
        String ddate = model.getValueAt(index, 3).toString();
        String adate = model.getValueAt(index, 4).toString();
        String dtime = model.getValueAt(index, 5).toString();
        String atime = model.getValueAt(index, 6).toString();
        double price = Double.parseDouble(model.getValueAt(index, 7).toString());
        String fclass = model.getValueAt(index, 8).toString();

        if (member == null) {
            SelectedFlight selectedFlight = new SelectedFlight(this.guest);

            String name = guest.getName();

            selectedFlight.flightnoLabel.setText(flightno);
            selectedFlight.dcityLabel.setText(dcity);
            selectedFlight.acityLabel.setText(acity);
            selectedFlight.ddateLabel.setText(ddate);
            selectedFlight.adateLabel.setText(adate);
            selectedFlight.dtimeLabel.setText(dtime);
            selectedFlight.atimeLabel.setText(atime);
            selectedFlight.priceLabel.setText(String.valueOf(price));
            selectedFlight.fclassLabel.setText(fclass);
            selectedFlight.customerName.setText(name);
            
        } 
        
        if (guest == null) {
            SelectedFlight selectedFlight = new SelectedFlight(this.member);

            String name = member.getName();
            selectedFlight.flightnoLabel.setText(flightno);
            selectedFlight.dcityLabel.setText(dcity);
            selectedFlight.acityLabel.setText(acity);
            selectedFlight.ddateLabel.setText(ddate);
            selectedFlight.adateLabel.setText(adate);
            selectedFlight.dtimeLabel.setText(dtime);
            selectedFlight.atimeLabel.setText(atime);
            selectedFlight.priceLabel.setText(String.valueOf(price));
            selectedFlight.fclassLabel.setText(fclass);
            selectedFlight.customerName.setText(name);
        }

        //selectedFlight.setVisible(true);
        //selectedFlight.pack();
        //selectedFlight.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        /*
        if (member.getName().equals(null)) {
            member.setName("Guest");
            selectedFlight.customerName.setText(name);
        }
         */
        dispose();
    }//GEN-LAST:event_selectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    //java.awt.EventQueue.invokeLater(new Runnable() {
    //  public void run() {
    //    new SearchFlight().setVisible(true);
    //  }
    //});
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
